### ISSUE TITLE
Module OFS unknown or incompatible

### ISSUE THREAD

**Issue by devz3r0** [ProgrammersOfVilnius/zope-export-tools#1]
hi,
I have to extract some python files out of some ZEXP files and read that this script supports it.
Unfortunately it wants to import a function via OFS which I installed via pip.
The version from pip has the structure 
/usr/lib/python2.7/site-packages/ofs
and the files:
base.py  base.pyc  command.py  command.pyc  factory.py  factory.pyc  __init__.py  __init__.pyc  local  remote

your script seems to request:
openat(AT_FDCWD, "/usr/lib/python2.7/dist-packages/OFS.x86_64-linux-gnu.so", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python2.7/dist-packages/OFS.so", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python2.7/dist-packages/OFSmodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python2.7/dist-packages/OFS.py", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/python2.7/dist-packages/OFS.pyc", O_RDONLY) = -1 ENOENT (No such file or directory)

with files I don't have either.

can you lead me to the correct module for it?

thanks Martin

**Comment by mgedmin** [comment]
The `OFS` used here is part of Zope 2 and should've been installed with `pip install Zope` (or, if you'd used the provided Makefile, by zc.buildout).  It's not related to the `ofs` package o PyPI.
